//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_KFC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public Nullable<int> idFood { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> totalPrice { get; set; }
    
        public virtual food food { get; set; }
    }
}
