//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_KFC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            this.carts = new HashSet<cart>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCategory { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> timeSellStart { get; set; }
        public Nullable<System.DateTime> timeSellEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        public virtual foodCategory foodCategory { get; set; }
    }
}
